/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

/**
 *
 * @author Stokler
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCadFornecedor = new javax.swing.JLabel();
        jPCadFor = new javax.swing.JPanel();
        jBCadFornecedor = new javax.swing.JButton();
        jPCadPro = new javax.swing.JPanel();
        jBCadProduto = new javax.swing.JButton();
        jBMFornecedor = new javax.swing.JButton();
        jBMProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLCadFornecedor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLCadFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCadFornecedor.setText("Fornecedor e Produto");

        jPCadFor.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Fornecedor"));

        jBCadFornecedor.setText("Cadastrar Fornecedor");

        javax.swing.GroupLayout jPCadForLayout = new javax.swing.GroupLayout(jPCadFor);
        jPCadFor.setLayout(jPCadForLayout);
        jPCadForLayout.setHorizontalGroup(
            jPCadForLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadForLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jBCadFornecedor)
                .addGap(169, 169, 169))
        );
        jPCadForLayout.setVerticalGroup(
            jPCadForLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadForLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBCadFornecedor)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPCadPro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Produto"));

        jBCadProduto.setText("Cadastrar Produto");

        javax.swing.GroupLayout jPCadProLayout = new javax.swing.GroupLayout(jPCadPro);
        jPCadPro.setLayout(jPCadProLayout);
        jPCadProLayout.setHorizontalGroup(
            jPCadProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadProduto)
                .addGap(185, 185, 185))
        );
        jPCadProLayout.setVerticalGroup(
            jPCadProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadProLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jBCadProduto)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jBMFornecedor.setText("Mostrar Fornecedor");

        jBMProduto.setText("Mostrar Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLCadFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPCadFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPCadPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jBMFornecedor)
                        .addGap(96, 96, 96)
                        .addComponent(jBMProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCadFornecedor)
                .addGap(26, 26, 26)
                .addComponent(jPCadFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jPCadPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBMFornecedor)
                    .addComponent(jBMProduto))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadFornecedor;
    private javax.swing.JButton jBCadProduto;
    private javax.swing.JButton jBMFornecedor;
    private javax.swing.JButton jBMProduto;
    private javax.swing.JLabel jLCadFornecedor;
    private javax.swing.JPanel jPCadFor;
    private javax.swing.JPanel jPCadPro;
    // End of variables declaration//GEN-END:variables
}
